services:
  - type: web
    name: handyhemi-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: ep-tight-mud-a5gc91sf-pooler.us-east-2.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: Handy-Chemi
      - key: DB_USER
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: admin@chemico.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: web
    name: handyhemi-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://handyhemi-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 